sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  matrix:
  - INSTANCE=default-centos-65
  global:
    matrix:
    - COMMIT=${TRAVIS_COMMIT::8}
    DOCKER_PASS:
      secure: U8yySAM1o2TT2qb6KOTKvhokGpxQaZrUAvl4klD21p8pnA147Tg16GQg7wDYR5ePqJxxxi3d4OSOIBh06BuQuPKl71uyEo8FVtf79jGMIlie3NF2bPhMC91OVIMeIx6vpapZW8d/4jLMix/NekJn43irqr8ZDhnJhDQqq873+Uexslc2N2KLdFG6EePlszqkATYwhpOcLCXcxDwp5vaSZn6XgpGjqzPPaqp1VMQ64fuSg/2M+rZCc0fcASzmEhduQgDOyb3mAwRvfMVFU+rdvNq94lTVaqxWGHdAwZyLfXcPB5UFdmv9WmfqiRsBP+WVRxo1C1KxAgMDCiUjDIrd3OlenAyiuZCPEb6hOj+uOUjj50qgbcx5gjBYvcJ+0+WnqVPEB2ARST2tl3NSDg7lgS5ILMxomcD6AJyIES0ZHnSA0qGkr1Cp2UXtchgvd4CXexfZv4DOHor7cmuS4C/jZglIhH/zJ0TOVMJOaoLmEiYtxjuD0zk6uO7dxCnvNLJcoiKUhfIxwr2T1ExvHwDB2hKaNK/XM9Fgutqrw4E2EoeGSHDTtYv6/0ppwqdumvrFLv2/j8i+IXQlb0x6UGNMbsNRoOiMcMsvL7QSRMb/DG0zNQGVmZdnV9l77z6ZuJ0MfbHO96zM02zSrE8SUf8q7G1M8i62Kuz4txdXNn1C8Hw=
    DOCKER_USER:
      secure: PT8O6DWn3vWflwPfZgj9n268WcXgqp85pWZP2l8st6hjRXLHB31gUnIyNr75krDS4f/O68h9Bnjb418Oxy2VNCrZZSkNnlqtuj3PE6XHF5QlrjcrU9MTWmklbgWrcXiP1eI2R6pfugK/AGyJ3KQZq6Pt0gS3Q3A5zNQnJDp+fkYJL1TQCV1QyT0OCUcTmhmCB4wJ9vAEf7xpHWz0CZtcrS1m1FY3/1q+Foo8bIQhZmhxVh8dtA77mV1gOncPXEWYzK1H3k9xScLZVNcm0QxKtrSuW9PUE09w7vGL9LbW7S0WSGBIXgADPq3AmdKU6tf/odZ9eH4ztrckMYv1qsOxBymck3qmTHB8jhTY0A9U1GSSyaObM2W9lntDFy4lk85q9BPNZ7AVIQipX+m6jj3fyBiltvKaPDtN9hum15coFOLfPGUb/rmxQBigPyZmfWlk4emeuWEUDle9iTdBYlyxOggDGrCULG0sFsh7KPCLyFIo1EVdvpVZC+ZH71fDjzsULuLbspI5v1XPv6hqmaZYG7ark8/jipggmZSI3b2HxU7jBGFcX49MpyjhZcQ7le3sz1nXyr5jeTxwJrdgHXjfTvhrh4Zp8u2LY6l5uE9XNCcDmY6CZJt3fCjM6g8pSDp+/OulBhgaAQXn4YF1dcTD/fRJHK0+fzAAJubvzedRtTU=
    DOCKER_EMAIL:
      secure: o/h1kyc56dMFV6lOxisPnrWarnghw2nIZ5CAYyrGBQCxnEuF8bIbULPYCWw6qtrX+FoKOkTv/878AEyUx6a/riQN2RKfxJZooO9wFdJbHgrWvK/950QkYwpnn38xKb0XW7tm3gmIPJHBTw/IvhfcVa+9qGyO2FEx8hxRe1bqw+wR1emOfKtpXISAgGa5fxg5sO7r3kPzug674Tee25Eam3NDPu0hnD9ATReL0CBC/zWJyZDETOqEkfsobWlshIlGMS+n8tgB++kF1LgRHA3gavgLN9tKSleD/KDjd+quAtbPK82q4iNxM1tujt6dMY/3GXlZ2LgIufS4vL9Q3W0DCpPEjawZZTurraSfVJEe2WHcjdx8Tr6AstgoU2xaAUHVoJSpDkuJOP50eGEqPUzpEenZ+/km516bFul3klr+oON75cRTYejZg5J4hrW+ygwTsm8dzrSQLcymzlAXDAs8jQQ6ybjKdunyzwog2CPB2amtsMsGrvPgpwWboGduWIdNlaSkcB/X10hRr1/DT50tCDp1pAUN7SBniJy50jDmu0yMjJ3iNLxgcGmL6gmooIyyXnFiERIZzLKzsBBKGrolmRvb/ixURj7psrJApyLJRtTdRecRS6WRUWXZF28S/ROYjG6zZYvN4kbEGmTZmEH9i2FWtP3LCDeFxhCf6OdyXk4=
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- "/opt/chefdk/embedded/bin/chef --version"
- "/opt/chefdk/embedded/bin/cookstyle --version"
- "/opt/chefdk/embedded/bin/foodcritic --version"
- "/opt/chefdk/bin/chef exec rake"
- chef gem install kitchen-docker
script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify
  ${INSTANCE} ${INSTANCE}
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker commit fastqc_dep eaglegenomics/fastqc_dep:latest
- docker push eaglegenomics/fastqc_dep:latest
notifications:
  slack:
    rooms:
      secure: KZW2IXMXSPTCkIqcuRH3dEllcsAg88+fXeYsWjyKkfaOOk94mCYArcpHxPoMciE6tmOE+5aywLwnyoS1LedMgkdbHnCA4XmPfoofcPcKTC7vqVzygaD3B6lFvIebUXGUCdnPzsqzwAV+eKtrowuvNqOVGNzpaz811z+Yn9p+xQ7ijSHwXtBspdKS8kHWJv0CqPQMm88+hoIsRlDHHhVgxswTvqzipGNzO2AOgHVDAYuFU1fEw6NhhfNSNplhvm2OhZ2iARvhMXg2NaNIx0XHiV3axi++SDi5Oss5KmYBCKQPBuUqmrbnPjC3OrbAJGu88zqQDaQAU/bDGtQihfFG6gdpDM+7Vw+2mHShwRWG68aE6yVuiVK+IwqYHykNAqKDpvgGVr4QFZt8FDPX/FGAFl88Qi8SNPtkiQ8wqKVb6oGM54gxhHHAAfotHUZn4T+Eo4Flp3YlhfIZlwGGYXSw4ve+96WGYshNY+VPIulV9z+uEiqdstf/dwjgbyCiHPSH7EDKkchuz3l/XvsZKhH53G/5oDIGsfMDigJNzu0UJj/osdhrmwXzZpw2NGXhFe0ce4pdcqW50/ijJMsdWV9LohUYBXZ3iuyIkIdwbM/vThDpD5Q9cuc+FxOzftnAWbGoSsAjWU122RSaeQC2+T1aXOgCiqmralGsHF+YXZTqUMk=
