sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  matrix:
  - INSTANCE=default-centos-65
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: op040tIkS2re55qwzof/Gc8+iPrvwKdIEtwMfPheb5ELxNF6ID5rKrlpYunmkzhxx+cyL7kDFvB+mr9lh+IlzmLI0vVYy0y/T1a0gC0GEVd72ofrnmYO7y4k86aAA096GRY+ejhenTCuQnzH3d6AtOGvGCtnN/8Vw8kJMCu1K3ggIbnwrme/quCIb3MjTIPjbTp6mFB1aHcIamwBKSzJogyzy7FQKC0dIJlQculLKceZin4S8Y6g/mM+EPUXlyednVkD/1aG84nirn2BzMtZSaPkmQk+T1Wjdakm91yTz0h6BEQdrix4s0/4PIgEN7ANvj1jUPUCF+F/4kjHuZvVtSX6c1Q6J2o7agduzn14TvpmEeXONd2dN3TJSwKT/WchBapmcwEI0GMY4AsuuRzyT8hpYLeuOA1czs7Hfw7If1ixl0BBZ2CmRoehJYp3u2ClKwXamORi5DWbkQncs0GLOx/xGVOGkicK96Xw3frXnD8zXuE1vPNKP3mQs1nsLneEWPVhOm4MfcKiJwCNa6gq+e2ATpKpBHADrUy3+MkgcitoF/bLtsUSRWwE83ZbQsXmj0AuCWQZVYpkCP/8I9hqe6ihbTkJMw10B+/epGn7uxLAYBC4Gm6hq4BD9pgAfSxhXcn8qtznpXV/e7Q06+91w88k9sIB4ZbkwNyuQINXsGo=
    - secure: gn1KaHMUcDDvv5Bkzr+VH1RrxkZpuuDCBWBySM3EgiwnVWoPAczytGDNQThuy66cvpUTM56aUo73QvXaNuMIhXJ+RHzpbIPx1UUdoGMh0hNomf0A8LeRx9Kl9EeySdLHN7kS7e8eFY/9WZzejcOq1n1Iw0sAW1kw9ObZFSNrphrIJ/F1OuDjcJEiKfyTDY4Fc9lKN7eQ/A2A1uHi5+lFUnARNCRqMj944iOhjmmFNMaCb8+VRs5Ahu4tojL1HakoC7OiEsMraEbgRXzfBZW1VvVmzu4AnDI+4fgxMnGQexZ+C2dCKMd8RxTi0wLptD2t7MgTn2SdHKtpvMu9/a0p2Dx1/GDAOoe3xJcchNlYj+CB+mNC9mE/3BpNbujd1XfoadVJumrBp5/fKGUiudfJOEFadBjx/ewo6/qCLzrUoOkboWJDDhsBTTbMUlEP3tJdV2RqzBzfavXqt/SVHDL/9LH6xp15yt6AUE5keYnGrfhnMhrKDy6VOE8TRHbtoBMV2RtTojOZqEe1r7AvTVoupF/qVtP4T1n0lKxxO9aEdVBX/XiDU90lE1G9D1b15HfCpxhU0/g4doiu0B1PsKZIacOpaI5lvJB9jOJgct5PILJJPpdnlmpRXkA1spSb8MyLM98TXT6IybiGDywLiAE/S/YqhP8aWgz4Ish57uyVFZw=
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- "/opt/chefdk/embedded/bin/chef --version"
- "/opt/chefdk/embedded/bin/cookstyle --version"
- "/opt/chefdk/embedded/bin/foodcritic --version"
- "/opt/chefdk/bin/chef exec rake"
- chef gem install kitchen-docker
script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify
  ${INSTANCE} ${INSTANCE}
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker commit fastqc_dep eaglegenomics/fastqc_dep:latest
- docker push eaglegenomics/fastqc_dep:latest
notifications:
  slack:
    rooms:
      secure: KZW2IXMXSPTCkIqcuRH3dEllcsAg88+fXeYsWjyKkfaOOk94mCYArcpHxPoMciE6tmOE+5aywLwnyoS1LedMgkdbHnCA4XmPfoofcPcKTC7vqVzygaD3B6lFvIebUXGUCdnPzsqzwAV+eKtrowuvNqOVGNzpaz811z+Yn9p+xQ7ijSHwXtBspdKS8kHWJv0CqPQMm88+hoIsRlDHHhVgxswTvqzipGNzO2AOgHVDAYuFU1fEw6NhhfNSNplhvm2OhZ2iARvhMXg2NaNIx0XHiV3axi++SDi5Oss5KmYBCKQPBuUqmrbnPjC3OrbAJGu88zqQDaQAU/bDGtQihfFG6gdpDM+7Vw+2mHShwRWG68aE6yVuiVK+IwqYHykNAqKDpvgGVr4QFZt8FDPX/FGAFl88Qi8SNPtkiQ8wqKVb6oGM54gxhHHAAfotHUZn4T+Eo4Flp3YlhfIZlwGGYXSw4ve+96WGYshNY+VPIulV9z+uEiqdstf/dwjgbyCiHPSH7EDKkchuz3l/XvsZKhH53G/5oDIGsfMDigJNzu0UJj/osdhrmwXzZpw2NGXhFe0ce4pdcqW50/ijJMsdWV9LohUYBXZ3iuyIkIdwbM/vThDpD5Q9cuc+FxOzftnAWbGoSsAjWU122RSaeQC2+T1aXOgCiqmralGsHF+YXZTqUMk=
