name 'FastQC'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures FASTQC'
long_description 'Installs/Configures FASTQC'
version '1.0.1'

depends 'build-essential'
depends 'magic_shell'
depends 'java'
